# CapgMyo comparison

Select four random channels and compare with ENG

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

import gc
gc.collect()

import sys
sys.path.append('../../Share/')
sys.path.append('../../Share/Manual_processing/')
import Model, utils, Same_with_MATLAB, Feature_info

import capgmyo_modules
f_path = 'C:/Users/hml76/Desktop/Jupyter/Datasets/CapgMyo/DB_A_preproceesed/'

In [2]:
def inter_session_run(idx, Feat_B):
    ACC_lst = []

    for SUB in range(1,11): #10
        print('Sub {}'.format(SUB))
        rep_lst = []
        X_train, y_train, X_test, y_test = [], [], [], []

        for rep in rep_lst_1:
            X, y = capgmyo_modules.import_dataset(subject=SUB, rep=rep, path=f_path, win_len=123, win_inc=24, sel_four_ch=idx, feature_selection=Feat_B)
            X_train.append(X)
            y_train.append(y)

        for rep in rep_lst_2:
            X, y = capgmyo_modules.import_dataset(subject=SUB, rep=rep, path=f_path, win_len=123, win_inc=24, sel_four_ch=idx, feature_selection=Feat_B)
            X_test.append(X)
            y_test.append(y)

        X_train, y_train = np.concatenate(X_train, axis=0), np.concatenate(y_train, axis=0)
        X_test, y_test = np.concatenate(X_test, axis=0), np.concatenate(y_test, axis=0)

        print(X_train.shape, X_test.shape)

        if Feat_B:  #2D-CNN: input: 16, 4
            X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], X_train.shape[2], 1)
            X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], X_test.shape[2], 1)
            print(X_train.shape, X_test.shape)
            model = Model.Original_model(input_shape=X_train.shape[1:], num_class=8)

        else:
            X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
            X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)
            print(X_train.shape, X_test.shape)
            model = Model.Original_model_1DCNN(input_size=X_train.shape[1:], num_class=8)

        history, model = Model.Train_model(model, X_train, y_train, X_test, y_test, set_epoch=100, set_batch_size=128, Model_name='V0',
                                            set_verbose=False, save_model_set=False)
        acc = model.evaluate(X_test, y_test, verbose=0)[1]
        ACC_lst.append(acc)

    return ACC_lst

In [3]:
rep_lst_1 = [1,6] #random - for test / train => our ENG has only one session (20 reps each, but here it has 10 so we use two sessions)
rep_lst_2 = [4,8] #random - for test / train

In [4]:
idx = np.random.choice(128, size=4, replace=False)
acc_lst_ch4 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch4), np.mean(acc_lst_ch4)

Sub 1
(16000, 4) (16000, 4)
(16000, 4, 1) (16000, 4, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 33.41%
Maximum validation accuracy : 34.17%
Sub 2
(16000, 4) (16000, 4)
(16000, 4, 1) (16000, 4, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 28.53%
Maximum validation accuracy : 27.13%
Sub 3
(16000, 4) (16000, 4)
(16000, 4, 1) (16000, 4, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 25.87%
Maximum validation accuracy : 21.36%
Sub 4
(16000, 4) (16000, 4)
(16000, 4, 1) (16000, 4, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 23.13%
Maximum validation accuracy : 26.37%
Sub 5
(16000, 4) (16000, 4)
(16000, 4, 1) (16000, 4, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 25.62%
Maximum validation accuracy : 20.72%
Sub 6
(16000, 4) (16000, 4)
(16000, 4, 1) (16000, 4, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 32.62%
Maximum validation accuracy : 26.18%
Sub 

(array([0.34175   , 0.27125001, 0.2135625 , 0.26374999, 0.2071875 ,
        0.26181251, 0.3273125 , 0.20125   , 0.23475   , 0.180875  ]),
 np.float64(0.2503500014543533))

In [5]:
idx = np.random.choice(128, size=3, replace=False)
acc_lst_ch3 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch3), np.mean(acc_lst_ch3)

Sub 1
(16000, 3) (16000, 3)
(16000, 3, 1) (16000, 3, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 23.78%
Maximum validation accuracy : 23.31%
Sub 2
(16000, 3) (16000, 3)
(16000, 3, 1) (16000, 3, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 23.81%
Maximum validation accuracy : 21.81%
Sub 3
(16000, 3) (16000, 3)
(16000, 3, 1) (16000, 3, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 33.31%
Maximum validation accuracy : 34.91%
Sub 4
(16000, 3) (16000, 3)
(16000, 3, 1) (16000, 3, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 26.01%
Maximum validation accuracy : 28.82%
Sub 5
(16000, 3) (16000, 3)
(16000, 3, 1) (16000, 3, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 22.62%
Maximum validation accuracy : 18.99%
Sub 6
(16000, 3) (16000, 3)
(16000, 3, 1) (16000, 3, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 27.52%
Maximum validation accuracy : 25.11%
Sub 

(array([0.23306251, 0.21806251, 0.3490625 , 0.28825   , 0.1899375 ,
        0.25106251, 0.23025   , 0.2858125 , 0.27937499, 0.1381875 ]),
 np.float64(0.2463062509894371))

In [6]:
idx = np.random.choice(128, size=2, replace=False)
acc_lst_ch2 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch2), np.mean(acc_lst_ch2)

Sub 1
(16000, 2) (16000, 2)
(16000, 2, 1) (16000, 2, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 23.68%
Maximum validation accuracy : 23.27%
Sub 2
(16000, 2) (16000, 2)
(16000, 2, 1) (16000, 2, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 24.47%
Maximum validation accuracy : 25.31%
Sub 3
(16000, 2) (16000, 2)
(16000, 2, 1) (16000, 2, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 25.56%
Maximum validation accuracy : 26.43%
Sub 4
(16000, 2) (16000, 2)
(16000, 2, 1) (16000, 2, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 23.07%
Maximum validation accuracy : 25.48%
Sub 5
(16000, 2) (16000, 2)
(16000, 2, 1) (16000, 2, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 22.73%
Maximum validation accuracy : 18.28%
Sub 6
(16000, 2) (16000, 2)
(16000, 2, 1) (16000, 2, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 24.19%
Maximum validation accuracy : 23.67%
Sub 

(array([0.23275   , 0.25312501, 0.26431251, 0.25481251, 0.18275   ,
        0.2366875 , 0.18449999, 0.16312499, 0.1856875 , 0.18737499]),
 np.float64(0.214512500166893))

In [7]:
idx = np.random.choice(128, size=1, replace=False)
acc_lst_ch1 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch1), np.mean(acc_lst_ch1)

Sub 1
(16000, 1) (16000, 1)
(16000, 1, 1) (16000, 1, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.71%
Maximum validation accuracy : 12.5%
Sub 2
(16000, 1) (16000, 1)
(16000, 1, 1) (16000, 1, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 16.16%
Maximum validation accuracy : 17.81%
Sub 3
(16000, 1) (16000, 1)
(16000, 1, 1) (16000, 1, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 21.42%
Maximum validation accuracy : 20.27%
Sub 4
(16000, 1) (16000, 1)
(16000, 1, 1) (16000, 1, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 21.03%
Maximum validation accuracy : 23.83%
Sub 5
(16000, 1) (16000, 1)
(16000, 1, 1) (16000, 1, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 17.55%
Maximum validation accuracy : 15.51%
Sub 6
(16000, 1) (16000, 1)
(16000, 1, 1) (16000, 1, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 20.28%
Maximum validation accuracy : 20.27%
Sub 7

(array([0.125     , 0.1780625 , 0.2026875 , 0.2383125 , 0.15512501,
        0.20275   , 0.137375  , 0.155     , 0.1749375 , 0.125     ]),
 np.float64(0.16942500025033952))

In [8]:
idx = np.random.choice(128, size=128, replace=False)
acc_lst_ch128 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch128), np.mean(acc_lst_ch128)

Sub 1
(16000, 128) (16000, 128)
(16000, 128, 1) (16000, 128, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 18.77%
Maximum validation accuracy : 26.64%
Sub 2
(16000, 128) (16000, 128)
(16000, 128, 1) (16000, 128, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 16.55%
Maximum validation accuracy : 19.53%
Sub 3
(16000, 128) (16000, 128)
(16000, 128, 1) (16000, 128, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 61.94%
Maximum validation accuracy : 65.74%
Sub 4
(16000, 128) (16000, 128)
(16000, 128, 1) (16000, 128, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.59%
Maximum validation accuracy : 12.5%
Sub 5
(16000, 128) (16000, 128)
(16000, 128, 1) (16000, 128, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.69%
Maximum validation accuracy : 12.5%
Sub 6
(16000, 128) (16000, 128)
(16000, 128, 1) (16000, 128, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 62

(array([0.2664375 , 0.1953125 , 0.6574375 , 0.125     , 0.125     ,
        0.58537501, 0.125     , 0.125     , 0.45912501, 0.125     ]),
 np.float64(0.2788687527179718))

In [9]:
idx = np.random.choice(128, size=120, replace=False)
acc_lst_ch120 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch120), np.mean(acc_lst_ch120)

Sub 1
(16000, 120) (16000, 120)
(16000, 120, 1) (16000, 120, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 40.97%
Maximum validation accuracy : 45.34%
Sub 2
(16000, 120) (16000, 120)
(16000, 120, 1) (16000, 120, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 43.96%
Maximum validation accuracy : 48.93%
Sub 3
(16000, 120) (16000, 120)
(16000, 120, 1) (16000, 120, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.81%
Maximum validation accuracy : 12.5%
Sub 4
(16000, 120) (16000, 120)
(16000, 120, 1) (16000, 120, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 46.16%
Maximum validation accuracy : 56.35%
Sub 5
(16000, 120) (16000, 120)
(16000, 120, 1) (16000, 120, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.78%
Maximum validation accuracy : 12.5%
Sub 6
(16000, 120) (16000, 120)
(16000, 120, 1) (16000, 120, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 60

(array([0.45343751, 0.4893125 , 0.125     , 0.56349999, 0.125     ,
        0.57106251, 0.44168749, 0.50375003, 0.35624999, 0.461     ]),
 np.float64(0.40900000035762785))

In [10]:
idx = np.random.choice(128, size=110, replace=False)
acc_lst_ch110 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch110), np.mean(acc_lst_ch110)

Sub 1
(16000, 110) (16000, 110)
(16000, 110, 1) (16000, 110, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 53.09%
Maximum validation accuracy : 56.11%
Sub 2
(16000, 110) (16000, 110)
(16000, 110, 1) (16000, 110, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 41.93%
Maximum validation accuracy : 47.51%
Sub 3
(16000, 110) (16000, 110)
(16000, 110, 1) (16000, 110, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 52.67%
Maximum validation accuracy : 57.6%
Sub 4
(16000, 110) (16000, 110)
(16000, 110, 1) (16000, 110, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 46.27%
Maximum validation accuracy : 54.11%
Sub 5
(16000, 110) (16000, 110)
(16000, 110, 1) (16000, 110, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 42.34%
Maximum validation accuracy : 34.34%
Sub 6
(16000, 110) (16000, 110)
(16000, 110, 1) (16000, 110, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 5

(array([0.56106251, 0.47512501, 0.57599998, 0.541125  , 0.34343749,
        0.50362498, 0.125     , 0.125     , 0.453125  , 0.44837499]),
 np.float64(0.41518749594688414))

In [11]:
idx = np.random.choice(128, size=100, replace=False)
acc_lst_ch100 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch100), np.mean(acc_lst_ch100)

Sub 1
(16000, 100) (16000, 100)
(16000, 100, 1) (16000, 100, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 58.67%
Maximum validation accuracy : 62.56%
Sub 2
(16000, 100) (16000, 100)
(16000, 100, 1) (16000, 100, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 37.16%
Maximum validation accuracy : 47.03%
Sub 3
(16000, 100) (16000, 100)
(16000, 100, 1) (16000, 100, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 54.72%
Maximum validation accuracy : 57.05%
Sub 4
(16000, 100) (16000, 100)
(16000, 100, 1) (16000, 100, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.61%
Maximum validation accuracy : 12.5%
Sub 5
(16000, 100) (16000, 100)
(16000, 100, 1) (16000, 100, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.57%
Maximum validation accuracy : 12.5%
Sub 6
(16000, 100) (16000, 100)
(16000, 100, 1) (16000, 100, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 58

(array([0.62562501, 0.47025001, 0.57050002, 0.125     , 0.125     ,
        0.57256252, 0.46487501, 0.4246875 , 0.31268749, 0.4201875 ]),
 np.float64(0.41113750636577606))

In [12]:
idx = np.random.choice(128, size=90, replace=False)
acc_lst_ch90 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch90), np.mean(acc_lst_ch90)

Sub 1
(16000, 90) (16000, 90)
(16000, 90, 1) (16000, 90, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 56.22%
Maximum validation accuracy : 58.93%
Sub 2
(16000, 90) (16000, 90)
(16000, 90, 1) (16000, 90, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 47.0%
Maximum validation accuracy : 54.93%
Sub 3
(16000, 90) (16000, 90)
(16000, 90, 1) (16000, 90, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 55.66%
Maximum validation accuracy : 61.61%
Sub 4
(16000, 90) (16000, 90)
(16000, 90, 1) (16000, 90, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.73%
Maximum validation accuracy : 12.5%
Sub 5
(16000, 90) (16000, 90)
(16000, 90, 1) (16000, 90, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.51%
Maximum validation accuracy : 12.5%
Sub 6
(16000, 90) (16000, 90)
(16000, 90, 1) (16000, 90, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 60.41%
Maximum validation a

(array([0.58925003, 0.54925001, 0.61606252, 0.125     , 0.125     ,
        0.57475001, 0.5128125 , 0.125     , 0.47975001, 0.44506249]),
 np.float64(0.41419375538825987))

In [13]:
idx = np.random.choice(128, size=80, replace=False)
acc_lst_ch80 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch80), np.mean(acc_lst_ch80)

Sub 1
(16000, 80) (16000, 80)
(16000, 80, 1) (16000, 80, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 60.54%
Maximum validation accuracy : 66.1%
Sub 2
(16000, 80) (16000, 80)
(16000, 80, 1) (16000, 80, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 50.19%
Maximum validation accuracy : 54.87%
Sub 3
(16000, 80) (16000, 80)
(16000, 80, 1) (16000, 80, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 52.38%
Maximum validation accuracy : 56.01%
Sub 4
(16000, 80) (16000, 80)
(16000, 80, 1) (16000, 80, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 44.29%
Maximum validation accuracy : 56.44%
Sub 5
(16000, 80) (16000, 80)
(16000, 80, 1) (16000, 80, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 36.41%
Maximum validation accuracy : 31.84%
Sub 6
(16000, 80) (16000, 80)
(16000, 80, 1) (16000, 80, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 59.65%
Maximum validation

(array([0.66100001, 0.54868752, 0.56006253, 0.56443751, 0.31837499,
        0.53893751, 0.48281249, 0.25025001, 0.355625  , 0.4136875 ]),
 np.float64(0.46938750743865965))

In [14]:
idx = np.random.choice(128, size=70, replace=False)
acc_lst_ch70 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch70), np.mean(acc_lst_ch70)

Sub 1
(16000, 70) (16000, 70)
(16000, 70, 1) (16000, 70, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 58.52%
Maximum validation accuracy : 63.94%
Sub 2
(16000, 70) (16000, 70)
(16000, 70, 1) (16000, 70, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.65%
Maximum validation accuracy : 12.5%
Sub 3
(16000, 70) (16000, 70)
(16000, 70, 1) (16000, 70, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 53.35%
Maximum validation accuracy : 56.87%
Sub 4
(16000, 70) (16000, 70)
(16000, 70, 1) (16000, 70, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.61%
Maximum validation accuracy : 12.5%
Sub 5
(16000, 70) (16000, 70)
(16000, 70, 1) (16000, 70, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 39.9%
Maximum validation accuracy : 33.43%
Sub 6
(16000, 70) (16000, 70)
(16000, 70, 1) (16000, 70, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 57.31%
Maximum validation a

(array([0.6394375 , 0.125     , 0.5686875 , 0.125     , 0.33425   ,
        0.55274999, 0.499125  , 0.125     , 0.46481249, 0.125     ]),
 np.float64(0.35590624809265137))

In [15]:
idx = np.random.choice(128, size=60, replace=False)
acc_lst_ch60 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch60), np.mean(acc_lst_ch60)

Sub 1
(16000, 60) (16000, 60)
(16000, 60, 1) (16000, 60, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 58.23%
Maximum validation accuracy : 61.65%
Sub 2
(16000, 60) (16000, 60)
(16000, 60, 1) (16000, 60, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 51.54%
Maximum validation accuracy : 55.84%
Sub 3
(16000, 60) (16000, 60)
(16000, 60, 1) (16000, 60, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 54.39%
Maximum validation accuracy : 58.33%
Sub 4
(16000, 60) (16000, 60)
(16000, 60, 1) (16000, 60, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.91%
Maximum validation accuracy : 12.5%
Sub 5
(16000, 60) (16000, 60)
(16000, 60, 1) (16000, 60, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 36.66%
Maximum validation accuracy : 28.35%
Sub 6
(16000, 60) (16000, 60)
(16000, 60, 1) (16000, 60, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 54.37%
Maximum validation

(array([0.61650002, 0.55843753, 0.58331251, 0.125     , 0.28349999,
        0.51581252, 0.52837503, 0.40881249, 0.314125  , 0.125     ]),
 np.float64(0.405887508392334))

In [16]:
idx = np.random.choice(128, size=50, replace=False)
acc_lst_ch50 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch50), np.mean(acc_lst_ch50)

Sub 1
(16000, 50) (16000, 50)
(16000, 50, 1) (16000, 50, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 46.63%
Maximum validation accuracy : 49.97%
Sub 2
(16000, 50) (16000, 50)
(16000, 50, 1) (16000, 50, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 33.99%
Maximum validation accuracy : 38.1%
Sub 3
(16000, 50) (16000, 50)
(16000, 50, 1) (16000, 50, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 50.93%
Maximum validation accuracy : 55.12%
Sub 4
(16000, 50) (16000, 50)
(16000, 50, 1) (16000, 50, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 42.36%
Maximum validation accuracy : 47.69%
Sub 5
(16000, 50) (16000, 50)
(16000, 50, 1) (16000, 50, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 36.82%
Maximum validation accuracy : 30.77%
Sub 6
(16000, 50) (16000, 50)
(16000, 50, 1) (16000, 50, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 47.4%
Maximum validation 

(array([0.49968749, 0.38100001, 0.55118752, 0.47687501, 0.30774999,
        0.47343749, 0.39693749, 0.125     , 0.4305    , 0.125     ]),
 np.float64(0.37673749923706057))

In [17]:
idx = np.random.choice(128, size=40, replace=False)
acc_lst_ch40 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch40), np.mean(acc_lst_ch40)

Sub 1
(16000, 40) (16000, 40)
(16000, 40, 1) (16000, 40, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 49.12%
Maximum validation accuracy : 50.39%
Sub 2
(16000, 40) (16000, 40)
(16000, 40, 1) (16000, 40, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 34.53%
Maximum validation accuracy : 33.43%
Sub 3
(16000, 40) (16000, 40)
(16000, 40, 1) (16000, 40, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 55.62%
Maximum validation accuracy : 57.93%
Sub 4
(16000, 40) (16000, 40)
(16000, 40, 1) (16000, 40, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 39.89%
Maximum validation accuracy : 48.34%
Sub 5
(16000, 40) (16000, 40)
(16000, 40, 1) (16000, 40, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 33.71%
Maximum validation accuracy : 27.11%
Sub 6
(16000, 40) (16000, 40)
(16000, 40, 1) (16000, 40, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 54.94%
Maximum validatio

(array([0.50393748, 0.3343125 , 0.5793125 , 0.48343751, 0.27106249,
        0.50650001, 0.3684375 , 0.125     , 0.4531875 , 0.125     ]),
 np.float64(0.3750187486410141))

In [18]:
idx = np.random.choice(128, size=30, replace=False)
acc_lst_ch30 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch30), np.mean(acc_lst_ch30)

Sub 1
(16000, 30) (16000, 30)
(16000, 30, 1) (16000, 30, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 54.46%
Maximum validation accuracy : 57.73%
Sub 2
(16000, 30) (16000, 30)
(16000, 30, 1) (16000, 30, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 41.99%
Maximum validation accuracy : 45.66%
Sub 3
(16000, 30) (16000, 30)
(16000, 30, 1) (16000, 30, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 49.46%
Maximum validation accuracy : 53.73%
Sub 4
(16000, 30) (16000, 30)
(16000, 30, 1) (16000, 30, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 21.96%
Maximum validation accuracy : 26.39%
Sub 5
(16000, 30) (16000, 30)
(16000, 30, 1) (16000, 30, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 37.14%
Maximum validation accuracy : 33.18%
Sub 6
(16000, 30) (16000, 30)
(16000, 30, 1) (16000, 30, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 54.04%
Maximum validatio

(array([0.57725   , 0.45656249, 0.53731251, 0.26387501, 0.3318125 ,
        0.504875  , 0.35887501, 0.125     , 0.231125  , 0.125     ]),
 np.float64(0.35116875171661377))

In [4]:
idx = np.random.choice(128, size=20, replace=False)
acc_lst_ch20 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch20), np.mean(acc_lst_ch20)

Sub 1
(16000, 20) (16000, 20)
(16000, 20, 1) (16000, 20, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 42.88%
Maximum validation accuracy : 41.19%
Sub 2
(16000, 20) (16000, 20)
(16000, 20, 1) (16000, 20, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 43.14%
Maximum validation accuracy : 46.88%
Sub 3
(16000, 20) (16000, 20)
(16000, 20, 1) (16000, 20, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.86%
Maximum validation accuracy : 12.5%
Sub 4
(16000, 20) (16000, 20)
(16000, 20, 1) (16000, 20, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 12.81%
Maximum validation accuracy : 12.5%
Sub 5
(16000, 20) (16000, 20)
(16000, 20, 1) (16000, 20, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 31.66%
Maximum validation accuracy : 29.73%
Sub 6
(16000, 20) (16000, 20)
(16000, 20, 1) (16000, 20, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 47.24%
Maximum validation 

(array([0.41187501, 0.46875   , 0.125     , 0.125     , 0.2973125 ,
        0.43512499, 0.34306249, 0.37825   , 0.3125    , 0.26131251]),
 np.float64(0.3158187508583069))

In [5]:
idx = np.random.choice(128, size=10, replace=False)
acc_lst_ch10 = inter_session_run(idx, Feat_B=False)
np.array(acc_lst_ch10), np.mean(acc_lst_ch10)

Sub 1
(16000, 10) (16000, 10)
(16000, 10, 1) (16000, 10, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 40.2%
Maximum validation accuracy : 42.56%
Sub 2
(16000, 10) (16000, 10)
(16000, 10, 1) (16000, 10, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 22.61%
Maximum validation accuracy : 23.16%
Sub 3
(16000, 10) (16000, 10)
(16000, 10, 1) (16000, 10, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 35.74%
Maximum validation accuracy : 31.3%
Sub 4
(16000, 10) (16000, 10)
(16000, 10, 1) (16000, 10, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 28.05%
Maximum validation accuracy : 32.21%
Sub 5
(16000, 10) (16000, 10)
(16000, 10, 1) (16000, 10, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 31.03%
Maximum validation accuracy : 25.31%
Sub 6
(16000, 10) (16000, 10)
(16000, 10, 1) (16000, 10, 1)
Start Training (total epochs: 100)...
Maximum training accuracy : 38.34%
Maximum validation 

(array([0.4255625 , 0.2315625 , 0.31299999, 0.32206249, 0.25306249,
        0.3458125 , 0.3154375 , 0.26456249, 0.37318751, 0.28237501]),
 np.float64(0.3126624971628189))

In [ ]:
import seaborn as sns

data = {"ch1": [0.125     , 0.1780625 , 0.2026875 , 0.2383125 , 0.15512501, 0.20275   , 0.137375  , 0.155     , 0.1749375 , 0.125     ],
    "ch2": [0.23275   , 0.25312501, 0.26431251, 0.25481251, 0.18275   , 0.2366875 , 0.18449999, 0.16312499, 0.1856875 , 0.18737499],
    "ch3": [0.23306251, 0.21806251, 0.3490625 , 0.28825   , 0.1899375 , 0.25106251, 0.23025   , 0.2858125 , 0.27937499, 0.1381875 ],
    "ch4": [0.34175   , 0.27125001, 0.2135625 , 0.26374999, 0.2071875 , 0.26181251, 0.3273125 , 0.20125   , 0.23475   , 0.180875  ],
    "ch10": acc_lst_ch10,
    "ch20": acc_lst_ch20,
    "ch30": [0.57725   , 0.45656249, 0.53731251, 0.26387501, 0.3318125 , 0.504875  , 0.35887501, 0.125     , 0.231125  , 0.125     ],
    "ch40": [0.50393748, 0.3343125 , 0.5793125 , 0.48343751, 0.27106249, 0.50650001, 0.3684375 , 0.125     , 0.4531875 , 0.125     ],
    "ch50": [0.49968749, 0.38100001, 0.55118752, 0.47687501, 0.30774999, 0.47343749, 0.39693749, 0.125     , 0.4305    , 0.125     ],
    "ch60": [0.61650002, 0.55843753, 0.58331251, 0.125     , 0.28349999, 0.51581252, 0.52837503, 0.40881249, 0.314125  , 0.125     ],
    "ch70": [0.6394375 , 0.125     , 0.5686875 , 0.125     , 0.33425   , 0.55274999, 0.499125  , 0.125     , 0.46481249, 0.125     ],
    "ch80": [0.66100001, 0.54868752, 0.56006253, 0.56443751, 0.31837499, 0.53893751, 0.48281249, 0.25025001, 0.355625  , 0.4136875 ],
    "ch90": [0.58925003, 0.54925001, 0.61606252, 0.125     , 0.125     , 0.57475001, 0.5128125 , 0.125     , 0.47975001, 0.44506249],
    "ch100": [0.62562501, 0.47025001, 0.57050002, 0.125     , 0.125     , 0.57256252, 0.46487501, 0.4246875 , 0.31268749, 0.4201875 ],
    "ch110": [0.56106251, 0.47512501, 0.57599998, 0.541125  , 0.34343749, 0.50362498, 0.125     , 0.125     , 0.453125  , 0.44837499],
    "ch120":  [0.45343751, 0.4893125 , 0.125     , 0.56349999, 0.125     , 0.57106251, 0.44168749, 0.50375003, 0.35624999, 0.461     ],
    "ch128":  [0.2664375 , 0.1953125 , 0.6574375 , 0.125     , 0.125     , 0.58537501, 0.125     , 0.125     , 0.45912501, 0.125     ],
}

df = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in data.items()]))
df_melted = df.melt(var_name="Channel", value_name="Accuracy")

# 시각화
plt.figure(figsize=(12,6), dpi=300)

# 박스플롯 (내부 평균선 제거, 깔끔한 스타일)
sns.boxplot(
    x="Channel", y="Accuracy", data=df_melted,
    palette="Set3",  # 색상 팔레트 (깔끔한 톤)
    width=0.6,
    fliersize=2,     # outlier 점 크기
    linewidth=1.2
)

# 각 채널 평균점 찍어주기 (논문용이면 강조)
sns.pointplot(x="Channel", y="Accuracy", data=df_melted, estimator="mean", color="black", markers="D",  # 다이아몬드 모양
    ci=None, join=False)

plt.xticks(rotation=45, ha="right", fontsize=11)
plt.yticks(fontsize=11)
plt.ylabel("Accuracy", fontsize=13)
plt.xlabel("Channel", fontsize=13)
plt.title("Accuracy Distribution per Channel", fontsize=14, pad=15)

sns.despine(offset=10, trim=True)  # 위/오른쪽 테두리 제거
plt.tight_layout()
plt.show()


In [ ]:
acc_lst_ch4 = [0.2697368487715721, 0.27960526943206787, 0.2697368413209915, 0.25986841320991516, 0.32236842811107635,0.30921052396297455, 0.23026316612958908, 0.33552631735801697, 0.32236842811107635]
acc_lst_ch3 = [0.30592105, 0.23355263, 0.21381579, 0.34539473, 0.22039474, 0.25      , 0.21381579, 0.25986843, 0.27631579]
acc_lst_ch2 = [0.24342105, 0.15131579, 0.25      , 0.20723684, 0.25986842, 0.26315789, 0.2993421 , 0.23026316, 0.25]
acc_lst_ch1 = [0.125     , 0.125     , 0.19078948, 0.125     , 0.15789474,        0.13486842, 0.21710526, 0.16776316, 0.15460526]

accs = [float(v) for v in [np.mean(acc_lst_ch1), np.mean(acc_lst_ch2), np.mean(acc_lst_ch3), np.mean(acc_lst_ch4)]]
stds = [float(v) for v in [np.std(acc_lst_ch1), np.std(acc_lst_ch2), np.std(acc_lst_ch3), np.std(acc_lst_ch4)]]

accs, stds

In [ ]:
import matplotlib.pyplot as plt

capgmyo_A = [0.15533625777777782,0.23940058333333333,  0.2576754388888889,  0.28874269293414223]
capgmyo_A_std = [0.03057531081066181,  0.03900728778730371,  0.042495222353503705,  0.033214012863790277]
eng_ours = [0.20592691832118565,  0.22991960992415747, 0.25636376980278227, 0.28052006037367714]
eng_ours_std = [0.05375169177908187, 0.08492193274795812, 0.08343234445005425, 0.09487073400413076]

x_label = [f'{i}-Channel' for i in range(1,5)]
x = range(len(x_label))

#plt.errorbar(x, capgmyo, yerr=capgmyo_std, fmt='o-', capsize=5, label="Capgmyo")
#plt.errorbar(x, eng_ours, yerr=eng_ours_std, fmt='o-', capsize=5, label="ENG Ours")
plt.plot(x, capgmyo_A, marker='o', label="Capgmyo-DB A")
plt.plot(x, eng_ours, marker='o', label="ENG")

plt.xticks(x, x_label)
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()


anp.array(acc_lst_ch3)atotal 10 sessions - training on 9 / testing on 1

ours: