# CapgMyo comparison

Select four random channels and compare with ENG

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

import gc
gc.collect()

import sys
sys.path.append('../../Share/')
sys.path.append('../../Share/Manual_processing/')
import Model, utils, Same_with_MATLAB, Feature_info

import capgmyo_modules
f_path = 'C:/Users/hml76/Desktop/Jupyter/Datasets/CapgMyo/DB_B_preproceesed/'

In [6]:
idx = np.random.choice(128, size=4, replace=False)
def inter_session_run(idx):
    ACC_lst = []

    for SUB in range(1,10):
        print('Sub {}'.format(SUB))
        rep_lst = []
        for rep in range(1,11):

            X_train, y_train, X_test, y_test = [], [], [], []
            for rep2 in range(1,11):
                if rep == rep2:
                    X_test, y_test = capgmyo_modules.import_dataset(subject=SUB, rep=rep, path=f_path, win_len=100, win_inc=50, sel_four_ch=idx)
                else:
                    X, y = capgmyo_modules.import_dataset(subject=SUB, rep=rep, path=f_path, win_len=100, win_inc=50, sel_four_ch=idx)
                    X_train.append(X)
                    y_train.append(y)
            X_train = np.concatenate(X_train, axis=0)
            y_train = np.concatenate(y_train, axis=0)

            X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
            X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

            model = Model.Original_model_1DCNN(input_size=X_train.shape[1:], num_class=8)

            history, model = Model.Train_model(model, X_train, y_train, X_test, y_test, set_epoch=100, set_batch_size=512, Model_name='V0',
                                                set_verbose=False, save_model_set=False)
            acc = model.evaluate(X_test, y_test, verbose=0)[1]
            rep_lst.append(acc)
            print(f'\t rep {rep} - acc lst : {rep_lst}')

        ACC_lst.append(np.mean(rep_lst))
    return ACC_lst

In [18]:
acc_lst_ch4 = [0.2822368383407593, 0.3624999955296516, 0.2532894715666771, 0.27828947752714156, 0.276973682641983, 0.2249999985098839, 0.33815789222717285,
            0.3611842095851898, 0.22763157933950423]

In [8]:
idx = np.random.choice(128, size=3, replace=False)
acc_lst_ch3 = inter_session_run(idx)

Sub 1
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 29.75%
Maximum validation accuracy : 25.0%
	 rep 1 - acc lst : [0.25]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 27.34%
Maximum validation accuracy : 27.63%
	 rep 2 - acc lst : [0.25, 0.2763157784938812]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 31.58%
Maximum validation accuracy : 31.58%
	 rep 3 - acc lst : [0.25, 0.2763157784938812, 0.31578946113586426]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 29.97%
Maximum validation accuracy : 25.0%
	 rep 4 - acc lst : [0.25, 0.2763157784938812, 0.31578946113586426, 0.25]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 25.58%
Maximum validation accuracy : 25.66%
	 rep 5 - acc lst : [0.25, 0.276315

In [ ]:
np.array(acc_lst_ch3)

In [9]:
idx = np.random.choice(128, size=2, replace=False)
acc_lst_ch2 = inter_session_run(idx)

Sub 1
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 29.75%
Maximum validation accuracy : 33.55%
	 rep 1 - acc lst : [0.33552631735801697]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 30.26%
Maximum validation accuracy : 58.55%
	 rep 2 - acc lst : [0.33552631735801697, 0.5855262875556946]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 31.58%
Maximum validation accuracy : 35.53%
	 rep 3 - acc lst : [0.33552631735801697, 0.5855262875556946, 0.3552631437778473]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 35.75%
Maximum validation accuracy : 51.32%
	 rep 4 - acc lst : [0.33552631735801697, 0.5855262875556946, 0.3552631437778473, 0.5131579041481018]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 29.17

In [10]:
idx = np.random.choice(128, size=1, replace=False)
acc_lst_ch1 = inter_session_run(idx)

Sub 1
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 26.97%
Maximum validation accuracy : 19.74%
	 rep 1 - acc lst : [0.19736842811107635]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 31.8%
Maximum validation accuracy : 28.29%
	 rep 2 - acc lst : [0.19736842811107635, 0.28289473056793213]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 22.81%
Maximum validation accuracy : 24.34%
	 rep 3 - acc lst : [0.19736842811107635, 0.28289473056793213, 0.2434210479259491]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 25.88%
Maximum validation accuracy : 25.0%
	 rep 4 - acc lst : [0.19736842811107635, 0.28289473056793213, 0.2434210479259491, 0.25]
Start Training (total epochs: 100)...
Finish Training! (Model is NOT saved)

Maximum training accuracy : 24.56%
Maximum val

In [19]:
np.array(acc_lst_ch4), np.mean(acc_lst_ch4)

(array([0.28223684, 0.3625    , 0.25328947, 0.27828948, 0.27697368,
        0.225     , 0.33815789, 0.36118421, 0.22763158]),
 np.float64(0.2894736828075515))

In [14]:
np.array(acc_lst_ch3), np.mean(acc_lst_ch3)

(array([0.25394737, 0.24210526, 0.23355263, 0.20460526, 0.24342105,
        0.20723684, 0.3125    , 0.34605263, 0.24736842]),
 np.float64(0.2545321641696824))

In [15]:
np.array(acc_lst_ch2), np.mean(acc_lst_ch2)

(array([0.43618421, 0.47302632, 0.26513157, 0.35263158, 0.21578948,
        0.16052631, 0.2618421 , 0.31381579, 0.24078947]),
 np.float64(0.3021929818722937))

In [16]:
np.array(acc_lst_ch1), np.mean(acc_lst_ch1)

(array([0.2381579 , 0.23355263, 0.175     , 0.20789474, 0.16381579,
        0.20657895, 0.21118421, 0.19407895, 0.23421053]),
 np.float64(0.20716374268134435))

anp.array(acc_lst_ch3)atotal 10 sessions - training on 9 / testing on 1

ours: